Vagrant.configure("2") do |config|

  config.vm.box = "tonyclemmey/windows11"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.121.130"

  config.vm.synced_folder File.expand_path("../images", __dir__), "C:/users/vagrant/shared_f", type: "rsync", disabled: false

  # 🔁 install_qemu.ps1 dosyasını da sanal makineye aktar
  config.vm.synced_folder File.expand_path("../windows11/scripts", __dir__), "C:/vagrant/scripts", type: "rsync"

  # rsync sonrası bilgi
  config.vm.provision "shell", inline: <<-SHELL
    echo "Paylaşımlı klasör rsync sonrası hazır."
  SHELL


  # 🔐 Ansible remoting hazırlığı
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    $url = "https://raw.githubusercontent.com/ansible/ansible-documentation/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"
    $file = "C:\\Windows\\Temp\\ConfigureRemotingForAnsible.ps1"
    Invoke-WebRequest -Uri $url -OutFile $file
    powershell.exe -ExecutionPolicy Bypass -File $file
  SHELL

  # ✅ QEMU kurulumu (install_qemu.ps1 çalıştırılır)
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    powershell.exe -ExecutionPolicy Bypass -File "C:\\vagrant\\scripts\\install_qemu.ps1"
  SHELL


   # Disk dosyalarını indir
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    powershell.exe -ExecutionPolicy Bypass -File "C:\\users\\vagrant\\shared_f\\download.ps1"
  SHELL



  config.vm.provider "libvirt" do |v|
    v.memory = "16384"
    v.cpus = "4"
    v.storage :file, path: 'extra-disk.qcow2', size: '25G'
    v.management_network_device = "tap0"
  end

end
