---
- name: Enable boot menu and make vda + vdb disks bootable
  hosts: baremetal
  become: true
  tasks:
    - name: Get VM XML definition
      command: virsh dumpxml libvirt_winvm
      register: vm_xml

    - name: Save XML file temporarily
      copy:
        content: "{{ vm_xml.stdout }}"
        dest: /tmp/libvirt_winvm.xml

    - name: Add <bootmenu enable="yes"/> to <os> block
      replace:
        path: /tmp/libvirt_winvm.xml
        regexp: '(<os[^>]*>)'
        replace: '\1\n  <bootmenu enable="yes"/>'

    - name: Remove <boot dev=.../> lines
      replace:
        path: /tmp/libvirt_winvm.xml
        regexp: '\s*<boot dev=.*?/>'
        replace: ''

    - name: Add <boot order="1"/> for vda
      replace:
        path: /tmp/libvirt_winvm.xml
        regexp: "(<target dev='vda' bus='virtio'/>)"
        replace: '\1\n      <boot order="2"/>'

    - name: Add <boot order="2"/> for vdb
      replace:
        path: /tmp/libvirt_winvm.xml
        regexp: "(<target dev='vdb' bus='virtio'/>)"
        replace: '\1\n      <boot order="1"/>'

    - name: Undefine the VM
      command: virsh undefine libvirt_winvm --managed-save
      ignore_errors: true

    - name: Redefine the VM using XML
      command: virsh define /tmp/libvirt_winvm.xml

    - name: Start the VM
      command: virsh start libvirt_winvm
