---
- name: Install QEMU on Debian-based system
  hosts: lin
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install QEMU and dependencies
      apt:
        name:
          - qemu-system-x86
          - qemu-utils
          - ovmf
        state: present
