Vagrant.configure("2") do |config|

  # === WINDOWS VM ===
  config.vm.define "winvm" do |win|

    win.vm.box = "tonyclemmey/windows11"
    win.vm.network "forwarded_port", guest: 80, host: 8080
    win.vm.network "private_network", ip: "192.168.121.130"

    win.vm.synced_folder File.expand_path("../images", __dir__), "C:/users/vagrant/shared_f", type: "rsync", disabled: false
    win.vm.synced_folder File.expand_path("../windows11/scriptswin", __dir__), "C:/vagrant/scripts", type: "rsync"

    win.vm.provision "shell", inline: <<-SHELL
      echo "Shared folder is ready after rsync."
    SHELL

    win.vm.provision "shell", privileged: true, inline: <<-SHELL
      $url = "https://raw.githubusercontent.com/ansible/ansible-documentation/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"
      $file = "C:\\Windows\\Temp\\ConfigureRemotingForAnsible.ps1"
      Invoke-WebRequest -Uri $url -OutFile $file
      powershell.exe -ExecutionPolicy Bypass -File $file
    SHELL

    win.vm.provision "shell", privileged: true, inline: <<-SHELL
      powershell.exe -ExecutionPolicy Bypass -File "C:\\vagrant\\scriptswin\\install_qemu.ps1"
    SHELL

    win.vm.provision "shell", privileged: true, inline: <<-SHELL
      powershell.exe -ExecutionPolicy Bypass -File "C:\\users\\vagrant\\shared_f\\download.ps1"
    SHELL

    win.vm.provider "libvirt" do |v|
      v.memory = "16384"
      v.cpus = 4
      v.storage :file, path: 'debian.qcow2', size: '25G'
      v.management_network_device = "tap0"
    end
  end

  # === UBUNTU VM ===
  config.vm.define "ubuntu", autostart: false do |ubuntu|

    ubuntu.vm.box = "generic-x64/ubuntu2204"
    ubuntu.vm.provision "shell", path: File.expand_path("../windows11/scriptsdeb/req.sh", __dir__)
    ubuntu.vm.network "private_network", ip: "192.168.121.20"
    ubuntu.vm.synced_folder ".", "/vagrant"
    ubuntu.vm.synced_folder File.expand_path("../images", __dir__), "/home/vagrant/shared_images", type: "rsync"

  end

end
